# Generated by Django 3.0.5 on 2020-04-17 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='descripption',
            new_name='description',
        ),
    ]
